name: newgame_mobile_simulator
description: NEWGAME Mobile Simulator — Preview web app di berbagai ukuran device secara real-time
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  # WebView untuk load localhost
  webview_flutter: ^4.7.0
  # Window management (desktop)
  window_manager: ^0.3.8
  # URL utils
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
