name: newgame_mobile
description: NEWGAME Mobile — Preview & mobile app untuk platform NEWGAME. Menampilkan web app dalam WebView dengan desain yang sama.
version: 0.1.4+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  connectivity_plus: ^6.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
